# Generated by Django 4.2 on 2023-05-01 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaznacheistvo_site', '0002_newsdetails_newsobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdetails',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('newsObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaznacheistvo_site.news')),
            ],
        ),
    ]
