# Generated by Django 4.2 on 2023-05-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaznacheistvo_site', '0003_remove_newsdetails_image_news_image_newsimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimages',
            name='description',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
