# Generated by Django 4.2.1 on 2023-05-08 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaznacheistvo_site', '0004_newsimages_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('questions', models.TextField(null=True)),
                ('questionsObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qwerty', to='kaznacheistvo_site.answer')),
            ],
        ),
    ]
