# Generated by Django 4.2.1 on 2023-05-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaznacheistvo_site', '0006_remove_answer_questionsobject_alter_answer_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('instagram', models.CharField(max_length=250)),
                ('facebook', models.CharField(max_length=250)),
                ('twiter', models.CharField(max_length=250)),
            ],
        ),
    ]
